stages:
  - test
  - build
  - deploy

variables:
  CGO_ENABLED: "1"  # Enable CGo for all stages

test:
  stage: test
  image: golang:1.23
  variables:
    CACHE_DISABLED: "true"
  script:
    - go test ./src/...
  cache: {}  # Explicitly disable cache

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - SEMVER_TAG=$(echo $CI_COMMIT_REF_NAME | cut -d/ -f2)
    - DOCKER_IMAGE=$CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$SEMVER_TAG
    - echo $DOCKER_IMAGE
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --build-arg CGO_ENABLED=1 -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
    - tags

.lint:
  stage: test
  image: golangci/golangci-lint:v1.56.2
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go
      - .cache
  before_script:
    - mkdir -p .cache
  script:
    - golangci-lint run 
      --timeout=5m 
      --modules-download-mode=readonly 
      --fast 
      --config=.golangci.yml 
      ./src/...
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  image: ghcr.io/tailscale/tailscale:latest
  before_script:
    # Install required packages
    - apk add --no-cache openssh
    - tailscaled --tun=userspace-networking &
    - sleep 5
    - tailscale up --authkey=$TAILSCALE_AUTHKEY --hostname=gitlab-runner-${CI_RUNNER_ID} --accept-routes --ssh

    # Setup SSH with verbose logging
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - SEMVER_TAG=$(echo $CI_COMMIT_REF_NAME | cut -d/ -f2)
    - DOCKER_IMAGE=$CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$SEMVER_TAG
  script:
    - scp -O docker-compose.yml $SSH_USER@$NAS_HOST:~/interest_bot/
    - |
      ssh $SSH_USER@$NAS_HOST "
        cd ~/interest_bot && \
        /usr/local/bin/docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY && \
        export DOCKER_IMAGE=$DOCKER_IMAGE && \
        export TELEGRAM_TOKEN=$TELEGRAM_TOKEN && \
        /usr/local/bin/docker-compose up -d --force-recreate"
  only:
    - tags