stages:
  - test
  - build

variables:
  DOCKER_IMAGE: $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  CGO_ENABLED: "1"  # Enable CGo for all stages

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_BUILDKIT: "1"  # Enable BuildKit for faster builds
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg CGO_ENABLED=1 -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
    - tags

test:
  stage: test
  image: golang:1.22
  script:
    - go test ./src/...
  only:
    - main
    - merge_requests

.lint:
  stage: test
  image: golangci/golangci-lint:v1.56.2
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go
      - .cache
  before_script:
    - mkdir -p .cache
  script:
    - golangci-lint run 
      --timeout=5m 
      --modules-download-mode=readonly 
      --fast 
      --config=.golangci.yml 
      ./src/...
  only:
    - main
    - merge_requests
