version: '3'
services:
  interest_bot:
    image: ${DOCKER_IMAGE}
    container_name: interest_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./data:/app/data
